Draft: Review StoredProc Reaction
drasi-project/drasi-platform pull request #103
Opened 2024-10-30 18:42 UTC by ruokun-niu

# Description

- Updated storedproc reaction provider
- StoredProc now accepts three different comands: AddedResultCommand, UpdatedResultCommand and DeletedResultCommand
- Added comments
- Created a test for the storedproc reaction in the `e2e` folder

## Type of change

- This pull request fixes a bug in Drasi and has an approved issue (issue link required).

Fixes: (https://dev.azure.com/azure-octo/Incubations/_boards/board/t/Drasi/User%20Stories?workitem=12558)

2024-11-04 21:35 UTC, danielgerlag requested changes

2024-11-04 21:35 UTC, danielgerlag commented on reactions/sql/storedproc-reaction/src/index.ts
> +const addedResultCommand: string = process.env["AddedResultCommand"] ?? '';
You could use `getConfigValue` instead of `process.env`

2024-11-04 21:35 UTC, danielgerlag commented on reactions/sql/storedproc-reaction/src/index.ts
> +    onControlEvent: onControlEvent
We are not using per query configs, so we could remove `parseQueryConfig: parseYaml`
We could also remove the control event handler if we are not doing anything in it.

2024-11-04 21:35 UTC, danielgerlag commented on reactions/sql/storedproc-reaction/src/index.ts
> +    knex.raw(query).then(() => {
you could make this function `async` and use `await`

2024-11-04 21:35 UTC, danielgerlag commented on e2e-tests/fixtures/storedproc-fixture.js
> +function storedprocReactionManifest(queryIds) {
this could be pure yaml in the directory of your specific scenario

2024-11-04 21:35 UTC, danielgerlag commented on e2e-tests/simple-scenario/my.test.js
> +test('Test StoredProc Reaction - AddedResultCommand', async () => {
Let's create a new scenario instead of extending the simple scenario.

2024-11-05 00:30 UTC, danielgerlag reviewed
You might also need to look into doing some kind of teardown per scenario, before it starts the next scenario.

2024-11-05 00:30 UTC, danielgerlag commented on e2e-tests/simple-scenario/resources.yaml
> +    CREATE TABLE "CommandResult" (
Do we still need this?

2024-11-05 00:30 UTC, danielgerlag commented on e2e-tests/storedproc-scenario/storedproc.test.js
> +  await new Promise(r => setTimeout(r, 15000));
Is there a better way we can do this rather than sleeping 35 seconds?
Could we check every 1 second and timeout after 30 seconds?
Something like the `.waitForChange` on on the signalr fixture.

2024-11-05 00:30 UTC, danielgerlag commented on reactions/sql/storedproc-reaction/src/index.ts
> +            executeStoredProcedure(addedResultCommand, queryArguments);
I think you need and `await` here

2024-11-05 00:30 UTC, danielgerlag commented on reactions/sql/storedproc-reaction/src/index.ts
> +        console.log(error);
If it fails, we probably want the exception to bubble up to the event handler, so that it will return a 500 error back to DAPR, so that the message will not be acknowledged off the queue.

2024-11-05 16:18 UTC, ruokun-niu commented on e2e-tests/simple-scenario/my.test.js
> +test('Test StoredProc Reaction - AddedResultCommand', async () => {
I investigated this a bit more and found out that jest actually does not allow two test scenarios to run sequentially. This sometimes caused a race condition in the postgres database and the e2e test to fail. 

I think maybe it is better to move the setup of the postgres database outside of the individual test scenarios and include it as a part of the cluster setup process?

2024-11-05 16:55 UTC, ruokun-niu commented on e2e-tests/simple-scenario/resources.yaml
> +    CREATE TABLE "CommandResult" (
The storedprocedure adds an item to this table. This is used to verify that the storedproc reaction is working

2024-11-05 17:08 UTC, danielgerlag commented on e2e-tests/simple-scenario/resources.yaml
> +    CREATE TABLE "CommandResult" (
but this is on the wrong scenario?

2024-11-05 17:13 UTC, danielgerlag commented on e2e-tests/simple-scenario/my.test.js
> +test('Test StoredProc Reaction - AddedResultCommand', async () => {
It would be better if scenarios did not share things. We could use different DNS names for different PG instances. I think you can run tests serially with jest: https://jestjs.io/docs/cli#--runinband

2024-11-05 17:44 UTC, ruokun-niu commented on e2e-tests/simple-scenario/my.test.js
> +test('Test StoredProc Reaction - AddedResultCommand', async () => {
Working on it right now

2024-11-06 23:29 UTC, danielgerlag reviewed
Looking good

2024-11-06 23:29 UTC, danielgerlag commented on cli/service/resources/default-reaction-providers.yaml
> +      AddedResultCommand:
In all of our sources, we have adopted camelCase for properties. Perhaps we should standardize?

2024-11-06 23:29 UTC, danielgerlag commented on e2e-tests/02-storedproc-scenario/storedproc.test.js
> +  await dbClient.end();
I think we need to clean up resources after each scenario.
This is missing from the test infrastructure.

2024-11-07 21:50 UTC, danielgerlag approved these changes

2024-11-08 15:07 UTC, agentofreality approved these changes

2024-11-08 19:06 UTC, merged