DRAFT: Review gremlin reaction
drasi-project/drasi-platform pull request #115
Opened 2024-11-14 19:15 UTC by ruokun-niu

# Description

_Please explain the changes you've made._

## Type of change

- This pull request fixes a bug in Drasi and has an approved issue (issue link required).
- This pull request adds or changes features of Drasi and has an approved issue (issue link required).
- This pull request is a minor refactor, code cleanup, test improvement, or other maintenance task and doesn't change the functionality of Drasi (issue link optional).

Fixes: #issue_number

2024-11-20 04:07 UTC, danielgerlag requested changes

2024-11-20 04:07 UTC, danielgerlag commented on reactions/gremlin/gremlin-reaction/Program.cs
> +using JanusGraph.Net;
Is there any reason we couldn't just stick to the generic Gremlin.Net driver?
https://docs.janusgraph.org/basics/connecting/dotnet/

2024-11-20 04:07 UTC, danielgerlag commented on reactions/gremlin/gremlin-reaction/gremlin-reaction.csproj
> +    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
What do we use Newtonsoft for? Could we just use System.Text.Json?

2024-11-20 04:07 UTC, danielgerlag commented on reactions/gremlin/gremlin-reaction/gremlin-reaction.csproj
> +    <PackageReference Include="JanusGraph.Net" Version="1.0.0" />
It would be great if we could just rely on the generic gremlin library, rather than something for a specific implementation.

2024-11-20 19:30 UTC, danielgerlag commented on reactions/gremlin/gremlin-reaction/Program.cs
> +			newCmd = newCmd.Replace($"@{param}", ExtractQueryResultValue(param, res));
Is there potential for an injection attack here?
Could we use a parameterized query?

2024-11-20 21:29 UTC, ruokun-niu commented on cli/service/resources/default-reaction-providers.yaml
> +      databasePrimaryKey:
It is actually the password of the gremlin server. Maybe we should change it to `gremlinPassword`?

2024-11-20 21:45 UTC, ruokun-niu commented on cli/service/resources/default-reaction-providers.yaml
> +      cosmosDatabaseContainerName:
The issue with this is that we need to use the cosmos database name and the container name to create a username for the Gremlin Client (wss://reactive-graph-demo.gremlin.cosmos.azure.com:443/)

2024-11-20 21:46 UTC, ruokun-niu commented on cli/service/resources/default-reaction-providers.yaml
> +      cosmosDatabaseContainerName:
If we want to be less cosmos specific, I guess we can replace these environment variables with one called `username`? Users will be responsible for generating their username in the specific format

2024-11-20 21:48 UTC, ruokun-niu commented on cli/service/resources/default-reaction-providers.yaml
> +      useCosmos:
Yeah I think we can determine this by checking if the host ends with `gremlin.azure.com`

2024-11-20 21:52 UTC, ruokun-niu commented on reactions/gremlin/gremlin-reaction/gremlin-reaction.csproj
> +    <PackageReference Include="JanusGraph.Net" Version="1.0.0" />
Let me try to remove this

2024-11-20 23:02 UTC, ruokun-niu commented on reactions/gremlin/gremlin-reaction/Program.cs
> +		if (useCosmos) {
removed

2024-11-20 23:17 UTC, ruokun-niu commented on reactions/gremlin/gremlin-reaction/Program.cs
> +	static void PrintStatusAttributes(IReadOnlyDictionary<string, object> attributes)
This is for logging the attributes of the status when an exception is encountered

2024-11-20 23:47 UTC, ruokun-niu commented on reactions/gremlin/gremlin-reaction/Program.cs
> +			newCmd = newCmd.Replace($"@{param}", ExtractQueryResultValue(param, res));
I think we can. 
Just double checking to make sure that we talking about the same thing, my understanding of a parameterized query is something like this
https://tinkerpop.apache.org/docs/current/reference/#parameterized-scripts

2024-11-21 02:38 UTC, danielgerlag commented on reactions/gremlin/gremlin-reaction/Program.cs
> +			newCmd = newCmd.Replace($"@{param}", ExtractQueryResultValue(param, res));
Yes, exactly like that 👍

2024-11-21 18:27 UTC, ruokun-niu commented on reactions/gremlin/gremlin-reaction/Program.cs
> +			newCmd = newCmd.Replace($"@{param}", ExtractQueryResultValue(param, res));
I have updated the `SubmitAsync` method to take in the cmd (as a string) and the parameters (as a dictionary)

2024-12-03 00:21 UTC, danielgerlag commented on e2e-tests/package.json
> +    "test:gremlin": "jest 03-gremlin-reaction-scenario/gremlin-reaction.test.js --detectOpenHandles",
I think if you want to run a specific test form the command line you could do something like:
```
npm test -- -t "<test name>"
```
I don't think we want a separate script for each test.

2024-12-03 00:26 UTC, danielgerlag commented on reactions/gremlin/gremlin-reaction/Services/GremlinService.cs
> +                if (param.StartsWith("before"))
Let's stick with strongly typed objects

2024-12-03 00:28 UTC, danielgerlag commented on reactions/gremlin/gremlin-reaction/Services/GremlinService.cs
> +            _logger.LogInformation($"\t[\"x-ms-total-request-charge\"] : {GetValueAsString(attributes, "x-ms-total-request-charge")}");
I think these are Cosmos specfic?

2024-12-03 17:56 UTC, ruokun-niu commented on e2e-tests/package.json
> +    "test:gremlin": "jest 03-gremlin-reaction-scenario/gremlin-reaction.test.js --detectOpenHandles",
Got it. I'll remove it

2025-01-02 22:12 UTC, danielgerlag commented on reactions/gremlin/gremlin-reaction/Services/GremlinService.cs
> +                    updatedResultCommandParams.Add(param, ExtractQueryResultValue(param.Substring(6), updatedResult.After));
is this removing a `after.`?

2025-01-02 23:39 UTC, ruokun-niu commented on reactions/gremlin/gremlin-reaction/Services/GremlinService.cs
> +                    updatedResultCommandParams.Add(param, ExtractQueryResultValue(param.Substring(6), updatedResult.After));
Yes

2025-01-02 23:41 UTC, danielgerlag commented on reactions/gremlin/gremlin-reaction/Services/GremlinService.cs
> +                    updatedResultCommandParams.Add(param, ExtractQueryResultValue(param.Substring(6), updatedResult.After));
What if there was a field in the result set called `afterburn` or something like that?

2025-01-03 00:00 UTC, ruokun-niu commented on reactions/gremlin/gremlin-reaction/Services/GremlinService.cs
> +                    updatedResultCommandParams.Add(param, ExtractQueryResultValue(param.Substring(6), updatedResult.After));
Oh yeah good catch, I think we should update the conditionals to check for before. and after.

2025-01-03 13:07 UTC, agentofreality approved these changes

2025-01-03 18:42 UTC, merged