Migrate query api to rust
drasi-project/drasi-platform pull request #45
Opened 2024-09-06 21:18 UTC by ruokun-niu

# Description

Migrate Query API to Rust

## Type of change

- This pull request adds or changes features of Drasi and has an approved issue (issue link required).

Fixes: #issue_number

2024-09-24 16:42 UTC, danielgerlag requested changes

2024-09-24 16:42 UTC, danielgerlag commented on infrastructure/comms-abstractions/src/comms.rs
> +    ) -> Result<reqwest::Response, Box<dyn std::error::Error>>;
I don't think we should include `reqwest::Response` as part of the API of drasi comms.  It tightly couples us to a specific library.

2024-09-24 16:42 UTC, danielgerlag commented on sources/shared/query-api/src/main.rs
> +        None => {}
We could log a warning if the trace headers are missing.

2024-09-24 16:45 UTC, ruokun-niu commented on infrastructure/comms-abstractions/src/comms.rs
> +    ) -> Result<reqwest::Response, Box<dyn std::error::Error>>;
How about a custom struct that contains the status code and/or the response body? Something like:
```rust
pub struct HttpResponse {
    pub status_code: u16,
    pub body: String,
}
```

2024-09-24 16:55 UTC, danielgerlag commented on infrastructure/comms-abstractions/src/comms.rs
> +    ) -> Result<reqwest::Response, Box<dyn std::error::Error>>;
That might make sense for the `Invoker`, but the publisher implementation could be one that does not use Http, if we choose to not use Dapr in the future, many messages brokers have their own protocols.
I think if a non success code comes from the Dapr sidecar, the publish was unsuccessful, and we just return an error, and if the body contains details, we include that in the error result.

2024-09-24 16:59 UTC, ruokun-niu commented on infrastructure/comms-abstractions/src/comms.rs
> +    ) -> Result<reqwest::Response, Box<dyn std::error::Error>>;
that makes sense. for a successful service invocation, maybe we can just return the body as Bytes?

2024-09-24 17:01 UTC, ruokun-niu commented on infrastructure/comms-abstractions/src/comms.rs
> +    ) -> Result<reqwest::Response, Box<dyn std::error::Error>>;
oh actually this is the publisher, we don't really need to return anything if the publish is successful

2024-09-24 17:01 UTC, ruokun-niu commented on infrastructure/comms-abstractions/src/comms.rs
> +    ) -> Result<reqwest::Response, Box<dyn std::error::Error>>;
Sorry I was think about the wrong thing

2024-09-24 18:17 UTC, danielgerlag commented on infrastructure/comms-abstractions/src/comms.rs
> +    ) -> Result<serde_json::Value, Box<dyn std::error::Error>>;
We can't assume the response will always be json

2024-09-25 23:25 UTC, danielgerlag approved these changes

2024-09-25 23:26 UTC, merged