Updated smoke-test script on github
drasi-project/drasi-platform pull request #91
Opened 2024-10-15 21:14 UTC by ruokun-niu

# Description

- Moved all smoke-test scripts and resources to be hosted on github instead of Azure storage blob
- Used `kubectl` to setup a database instead of using `helm`
- The smoke test will
  - Set up a postgres source, one continuous query and one result reaction
  - The query will retrieve all items that are in category A
  - Initially, there will be two items in the result set, one with ID 1 and one with ID3
  - Two entries will be added into the postgres database: one with ID 4 and category B, and one with ID 5 and category A
  - final result should have three items: ID 1, ID 3, and ID 5
- The smoke test will be run in both bash and powershell to ensure compatibility with both environments

When this gets merged into main, the smoke-test can be invoked by using the following commands
MacOS:
```bash
curl -fsSL https://raw.githubusercontent.com/drasi-project/drasi-platform/main/dev-tools/smoke-tests/smoke-test.sh | /bin/bash -s <namespace>
```
Windows powershell
```ps1
Invoke-Command -ScriptBlock ([scriptblock]::Create([System.Text.Encoding]::UTF8.GetString((New-Object Net.WebClient).DownloadData('https://raw.githubusercontent.com/drasi-project/drasi-platform/main/dev-tools/smoke-tests/smoke-test.ps1')))) -ArgumentList <namespace>
```

For now, if you want to test the script, run the following command (the file is hosted on a branch on my personal fork)
```bash
curl -fL https://raw.githubusercontent.com/ruokun-niu/drasi-platform/smoke-test-test/dev-tools/smoke-tests/smoke-test.sh | /bin/bash -s smoke
```

Logs from a successful bash run: https://gist.github.com/ruokun-niu/605eae11b9ec034285a2630f20521ea6
Logs from a successful powershell run: https://gist.github.com/ruokun-niu/724f1debfd276560356151a0295843a5

## Type of change

- This pull request is a minor refactor, code cleanup, test improvement, or other maintenance task and doesn't change the functionality of Drasi (issue link optional).

Fixes: #issue_number

2024-10-18 15:29 UTC, agentofreality requested changes
Are there any old smoke test files that need to be deleted from the repo?

2024-10-18 15:29 UTC, agentofreality commented on dev-tools/smoke-tests/cleanup-smoke-test.sh
Ideally, the source, query, and reaction should be deleted in reverse dependency order, although this is not going to matter right now, it will break when we do introduce dependency checks.

2024-10-18 15:29 UTC, agentofreality commented on dev-tools/smoke-tests/setup-smoke-test.sh
> +helm repo add bitnami https://charts.bitnami.com/bitnami 1>/dev/null
What is the comment in the PR about moving from helm to kubectl to setup db?

2024-10-18 15:48 UTC, ruokun-niu commented on dev-tools/smoke-tests/setup-smoke-test.sh
> +helm repo add bitnami https://charts.bitnami.com/bitnami 1>/dev/null
Oh sorry, this file was supposed to be deleted but was accidentally checked-in. The actual smoke test should be the 'smoke-test.sh' file

2024-10-18 15:49 UTC, ruokun-niu commented on dev-tools/smoke-tests/cleanup-smoke-test.sh
I will reverse the order

2024-10-18 16:45 UTC, ruokun-niu commented
> Are there any old smoke test files that need to be deleted from the repo?

Currently we dont have any old smoke test files in the Github repos. We can delete the ones that are stored in our storage blob once this PR gets merged

2024-10-22 20:41 UTC, agentofreality approved these changes

2024-10-23 14:08 UTC, agentofreality requested changes
Lets:
- put this in a folder called dev-tools/testing/platform-quick-test
- change file names from 'smoke-test-*' to 'platform-quick-test-*'

2024-10-23 14:08 UTC, agentofreality commented on dev-tools/smoke-tests/cleanup-smoke-test.sh
I notice there is no cleanup for PowerShell

2024-10-23 16:11 UTC, ruokun-niu commented
> Lets:
> 
> * put this in a folder called dev-tools/testing/quick-test-environment
> * change file names from 'smoke-test-_' to 'quick-test-environment-_'

I'll also update any occurences of "Smoke Test" to "Quick Test" so that it is consistent with the samples in the doc site

2024-10-23 21:45 UTC, agentofreality approved these changes

2024-10-23 21:47 UTC, danielgerlag approved these changes

2024-10-23 22:49 UTC, merged